# Generated by Django 4.2 on 2024-05-22 01:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_alter_comment_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="ip",
            field=models.GenericIPAddressField(null=True),
        ),
    ]
